import type { Context } from "../context.ts";
import { Client as Issue } from "./issues/mod.ts";
import { Client as IssueStatus } from "./issue-statuses/mod.ts";
import { Client as Project } from "./projects/mod.ts";
import { Client as Tracker } from "./trackers/mod.ts";
import { Client as IssueTemplate } from "./issue-templates/mod.ts";
import { Client as Wiki } from "./wiki-pages/mod.ts";
import { Client as Version } from "./versions/mod.ts";
import { Client as Role } from "./roles/mod.ts";
import { Client as Enumeration } from "./enumerations/mod.ts";
import { Client as CustomField } from "./custom-fields/mod.ts";
import { Client as Query } from "./queries/mod.ts";
import { Client as News } from "./news/mod.ts";
import { Client as User } from "./users/mod.ts";
import { Client as TimeEntry } from "./time-entries/mod.ts";
import { Client as IssueCategory } from "./issue-categories/mod.ts";
import { Client as Membership } from "./memberships/mod.ts";
import { Client as MyAccount } from "./my-account/mod.ts";
import { Client as Group } from "./groups/mod.ts";
import { Client as IssueRelation } from "./issue-relations/mod.ts";
import { Client as Journal } from "./journals/mod.ts";
import { Client as Attachment } from "./attachments/mod.ts";
import { Client as FileClient } from "./files/mod.ts";
import { Client as Search } from "./search/mod.ts";

export class Redmine {
  readonly #context: Context;
  readonly issue: Issue;
  readonly issueStatus: IssueStatus;
  readonly project: Project;
  readonly tracker: Tracker;
  readonly issueTemplate: IssueTemplate;
  readonly wiki: Wiki;
  readonly version: Version;
  readonly role: Role;
  readonly enumeration: Enumeration;
  readonly customField: CustomField;
  readonly query: Query;
  readonly news: News;
  readonly user: User;
  readonly timeEntry: TimeEntry;
  readonly issueCategory: IssueCategory;
  readonly membership: Membership;
  readonly myAccount: MyAccount;
  readonly group: Group;
  readonly issueRelation: IssueRelation;
  readonly journal: Journal;
  readonly attachment: Attachment;
  readonly file: FileClient;
  readonly search: Search;

  constructor(context: Context) {
    this.#context = context;
    this.issue = new Issue(this.#context);
    this.issueStatus = new IssueStatus(this.#context);
    this.project = new Project(this.#context);
    this.tracker = new Tracker(this.#context);
    this.issueTemplate = new IssueTemplate(this.#context);
    this.wiki = new Wiki(this.#context);
    this.version = new Version(this.#context);
    this.role = new Role(this.#context);
    this.enumeration = new Enumeration(this.#context);
    this.customField = new CustomField(this.#context);
    this.query = new Query(this.#context);
    this.news = new News(this.#context);
    this.user = new User(this.#context);
    this.timeEntry = new TimeEntry(this.#context);
    this.issueCategory = new IssueCategory(this.#context);
    this.membership = new Membership(this.#context);
    this.myAccount = new MyAccount(this.#context);
    this.group = new Group(this.#context);
    this.issueRelation = new IssueRelation(this.#context);
    this.journal = new Journal(this.#context);
    this.attachment = new Attachment(this.#context);
    this.file = new FileClient(this.#context);
    this.search = new Search(this.#context);
  }
}
