name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        with:
          release-type: simple
          package-name: deno_redmine
          include-v-in-tag: false
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
      - name: Setup deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        if: ${{ steps.release.outputs.release_created }}
      - name: Bump up jsr.json
        run: deno run --allow-write --allow-read internal/bumpup.ts jsr.json --next ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload Release Artifact
        run: deno publish --allow-dirty --config jsr.json
        if: ${{ steps.release.outputs.release_created }}
