name: deno test

on:
  workflow_run:
    workflows: ["deno basic ci"]
    types: [completed]

jobs:
  deno_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
      - name: run deno test
        run: deno task test
