name: deno test

on:
  workflow_run:
    workflows: ["deno basic ci"]
    types: [completed]

jobs:
  deno_test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: denoland/setup-deno@fa660b328d065f7683e7303976bd81e2d58e98ae # v1.4.1
      - name: run deno test
        run: deno task test
